name: Deploy to Firebase Hosting on PR

on: pull_request

jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm i

      - name: Bump patch version
        run: npm version patch --no-git-tag-version

      - name: Build
        run: npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          # La acción automáticamente detecta si es un PR y crea un canal de previsualización.
          # No necesitas 'args: deploy --only hosting:preview'.
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ATLAS_GYM_PARTNER }}'
          projectId: atlas-gym-partner # Es buena práctica especificar el project ID
          # No necesitas la sección 'env' para GCP_SA_KEY, ya que firebaseServiceAccount se pasa directamente en 'with'.
